version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
    working_directory: /home/circleci/project/server
    steps:
      - checkout
      - run: ls -R /home/circleci/project/server/.mvn
      - run: ./server/mvnw test
workflows:
  version: 2
  my_workflow:
    jobs:
      - build
# orbs:
#   maven: circleci/maven@1.1

# workflows:
#   maven_test:
#     jobs:
#       - maven/test
