version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: cd ./server
      - run: ls -la
      - run: ./mvnw test

workflows:
  version: 2
  my_workflow:
    jobs:
      - build
# orbs:
#   maven: circleci/maven@1.1

# workflows:
#   maven_test:
#     jobs:
#       - maven/test
