version: 2.1

jobs:
  build:
    working_directory: ~/project/server
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout:
          path: ~/project
      - run: ls -la /home/circleci/project/server
      - run: ls -la ~/project/server
      - run: ls -la .
      - run: ./mvnw test
workflows:
  version: 2
  my_workflow:
    jobs:
      - build
