version: 2.1

jobs:
  build:
    working_directory: ~/stomp-websocket-messenger
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout:
          path: ~/stomp-websocket-messenger/server
      - run: ls -la /home/circleci/stomp-websocket-messenger/server
      - run: ls -la ~/stomp-websocket-messenger/server
      - run: ./mvnw test
workflows:
  version: 2
  my_workflow:
    jobs:
      - build
# orbs:
#   maven: circleci/maven@1.1

# workflows:
#   maven_test:
#     jobs:
#       - maven/test
